
about :

  name : wCommandsConfig
  description : Collection of CLI commands to manage config. Use the module to mixin commands add/remove/delete/set to a class.
  version : 0.3.5
  enabled : 1
  interpreters :
  - nodejs >= 6.0.0
  - chrome >= 60.0.0
  - firefox >= 60.0.0
  keywords :
  - wTools

execution :

  scripts :
    test : wtest staging
    docgen : wdocgen staging

path :

  repository : git+https://github.com/Wandalen/wCommandsConfig.git
  bugs : https://github.com/Wandalen/wCommandsConfig/issues
  entry.debug : {path::out.debug}/dwtools/abase/____
  entry.release : {path::out.release}/dwtools/abase/____

build :

  .debug.raw.export :
    default : 1
    setting :
      debug : 1
      raw : 1
      export : 1
      filesPath : path::out.debug
      entryPath : path::entry.debug
    steps :
      - build::.debug
      - step::export

  .release.compiled.export :
    setting :
      debug : 0
      raw : 0
      export : 1
      filesPath : path::out.release
      entryPath : path::entry.release
    steps :
      - build::.release.compiled
      - step::export

