
about :

  name : wCommandsConfig
  description : Collection of CLI commands to manage config. Use the module to mixin commands add/remove/delete/set to a class.
  version : 0.3.16
  enabled : 1
  interpreters :
  - nodejs >= 6.0.0
  - chrome >= 60.0.0
  - firefox >= 60.0.0
  keywords :
  - wTools

execution :

  scripts :
    test : wtest staging
    docgen : wdocgen staging

path :

  repository : git+https://github.com/Wandalen/wCommandsConfig.git
  bugs : https://github.com/Wandalen/wCommandsConfig/issues

step :

  export.proto :
    inherit : export
    export : path::proto
    tar : 0
    criterion :
      debug : 1
      proto : 1

build :

  proto.export :
    criterion :
      default : 1
      debug : 1
      raw : 1
      proto : 1
      export : 1
      tar : 1
    steps :
      - build::debug.raw
      - step::export.proto

